# List end points with node exporter

- targets:
       - 172.17.0.2:9100
  labels:
       cluster: cluster1
       dc: dc1
- targets:
       - 172.17.0.3:9100
  labels:
       cluster: cluster1
       dc: dc2
