global:
  scrape_interval: 5s # By default, scrape targets every 5 second.
  scrape_timeout: 4s # Timeout before trying to scape a target again

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'scylla-monitor'

scrape_configs:
- job_name: scylla
  honor_labels: true
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_servers.yml

- job_name: node_exporter
  honor_labels: true
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/node_exporter_servers.yml
