global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'scylla-monitor'

scrape_configs:
- job_name: scylla
  honor_labels: true
  static_configs:
  - targets: ["127.0.0.1:9180"]
- job_name: node_exporter
  honor_labels: true
  static_configs:
  - targets: ['127.0.0.1:9100']

## two servers example: - targets: ["172.17.0.3:9103","172.17.0.2:9103"]
